### ISSUE TITLE
你好，想请教下你是怎么找到api接口的。有没有自动化的工具。还是手动找的。

### ISSUE THREAD

**Issue by xx2211** [YunYouJun/export-nideriji#5]

**Comment by YunYouJun** [comment]
fiddler 加 Postman。

请参见 https://www.yunyoujun.cn/note/export-nideriji-and-import-1diary/ 。

**Comment by xx2211** [comment]
> fiddler 加 Postman。
> 
> 请参见 https://www.yunyoujun.cn/note/export-nideriji-and-import-1diary/ 。

好的，感谢
