### ISSUE TITLE
导入一本日记时间好像有问题，会差几个小时

### ISSUE THREAD

**Issue by xxx-jjw** [YunYouJun/export-nideriji#6]

**Comment by YunYouJun** [comment]
我认为该问题的结果可以接受。

以及我已经迁移完毕，所以没有重新复现的打算。
如果您有兴趣可以提 PR。

**Comment by xx2211** [comment]
我发现原因了，是因为，创建日记时指定的日期不是今天时，两种软件的处理不一样。
你的日记是createdate是指定的日期，但createtime是今天日期。一本日记的createtime就是指定的日期。
我提一个pr吧。

**Comment by dulk-dev** [comment]
你的日记采用的时间是utc，dayjs用的是local，所以除了老哥提的这个问题，还有时间格式的转换问题，会有偏差，我再提个pr吧
