### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by zyfeleven** [YunYouJun/export-nideriji#8]
一直报错Error: certificate has expired是啥情况？已经在登陆页面copy了最新的csrf了。

**Comment by YunYouJun** [comment]
也许是域名的证书过期了，可以使用 http 替代 https。

亦或是更新了别的验证策略，我迁移完没有再用过了。

**Comment by zyfeleven** [comment]
好的谢谢

**Comment by dulk-dev** [comment]
自己也遇到了，百度了下解决了，贴一下帮助后面还需要的伙伴
axios.js中新增忽略验证

const https = require('https');
const agent = new https.Agent({
  rejectUnauthorized: false
});
// ...
axios.defaults.httpsAgent = agent

另外感谢云游君的工具开发和共享，谢谢-v-

**Comment by YunYouJun** [comment]
@deng-cc 可以考虑提个 PR 修复。
